#!/usr/bin/env node
/* Build dict-en.js and dict-es.js from npm word-list packages.
   Run once; commit the resulting asset files. Re-run when you want to
   refresh the wordlists.

   Usage:
     npm install --no-save --prefix /tmp/dictbuild \
       an-array-of-english-words an-array-of-spanish-words lz-string
     node tools/build-dicts.js
*/

const path = require("path");
const fs = require("fs");

const PREFIX = process.env.DICTBUILD_PREFIX || "/tmp/dictbuild";
const requireFromPrefix = (mod) => require(path.join(PREFIX, "node_modules", mod));

const enWords = requireFromPrefix("an-array-of-english-words");
const esWords = requireFromPrefix("an-array-of-spanish-words");
const LZString = requireFromPrefix("lz-string");

function clean(arr) {
  const set = new Set();
  for (const w of arr) {
    if (typeof w !== "string") continue;
    const lower = w.toLowerCase().trim();
    if (!lower) continue;
    if (lower.length < 2 || lower.length > 30) continue;
    if (!/^[a-záéíóúñüç'-]+$/i.test(lower)) continue;
    set.add(lower);
  }
  return Array.from(set).sort();
}

function writeAsset(filename, words, varName, sourceCredit) {
  const payload = words.join("\n");
  const compressed = LZString.compressToBase64(payload);
  const header = `"use strict";
/* Bestscreen wordlist asset — auto-generated by tools/build-dicts.js.
   ${sourceCredit}
   ${words.length.toLocaleString()} words. Decompressed payload size: ${payload.length.toLocaleString()} chars.
   Do not edit by hand — re-run the build script. */
`;
  const body = `const ${varName} = ${JSON.stringify(compressed)};\n`;
  fs.writeFileSync(filename, header + body);
  console.log(`Wrote ${filename} — ${words.length} words, ${compressed.length.toLocaleString()} bytes compressed.`);
}

const enCleaned = clean(enWords);
const enSample = enCleaned.filter(w => w.length <= 15);
writeAsset("dict-en.js", enSample, "DICT_EN_RAW",
  "Source: dwyl/an-array-of-english-words (MIT). Sampled to length <= 15.");

const esCleaned = clean(esWords);
const esSample = esCleaned.filter(w => w.length <= 15);
writeAsset("dict-es.js", esSample, "DICT_ES_RAW",
  "Source: words/an-array-of-spanish-words (MIT). Sampled to length <= 15.");

console.log("Done.");
